@startuml
'https://plantuml.com/use-case-diagram
skinparam actorStyle awesome
left to right direction

rectangle StartMenu {
usecase "Create or login to account" as (UC1)
note top of (UC1)
Login information is stored
end note
}
User -down-> (UC1)
rectangle AdminMenu {
rectangle UserMenu {
usecase "Search Movie or Series" as (UC2-1)
usecase "Search all media in chosen category" as (UC2-2)
usecase "Show all watched media" as (UC2-3)
usecase "Show all saved media" as (UC2-4)
usecase "Choose media" as (UC2-5)
}
usecase "Add new media" as (UC4-1)
usecase "Remove media" as (UC4-2)
}

Admin -down-> (UC1)

rectangle MediaMenu{
usecase "Play media" as (UC3-1)
usecase "Save media to watchlist" as (UC3-2)
usecase "Remove media from watchlist" as (UC3-3)
note bottom of (UC3-1) : Media is added to watched list
}

(UC1) --> (UC2-1)
(UC1) --> (UC2-2)
(UC1) --> (UC2-3)
(UC1) --> (UC2-4)
(UC1) ----> (UC4-1) : if admin
(UC1) ----> (UC4-2) : if admin
(UC2-2) --> (UC2-5)
(UC2-3) --> (UC2-5)
(UC2-4) --> (UC2-5)
(UC2-5) --> (UC3-1)
(UC2-5) --> (UC3-2)
(UC2-5) --> (UC3-3)

@enduml