@startuml
'https://plantuml.com/use-case-diagram
skinparam actorStyle awesome
left to right direction

rectangle StartMenu {
usecase "Create or login to account" as (UC1)
note top of (UC1)
Login information is stored
end note
}
User -down-> (UC1)
rectangle AdminMenu {
rectangle UserMenu {
usecase "Search Movie or Series" as (UC2)
usecase "Show all media in category" as (UC3)
usecase "Show all watched media" as (UC4)
usecase "Show all saved media" as (UC5)
usecase "Choose media" as (UC6)
}
usecase "Add new media" as (UC10)
usecase "Remove media" as (UC11)
}

Admin -down-> (UC1)

rectangle MediaMenu{
usecase "Play media" as (UC7)
usecase "Save media to watchlist" as (UC8)
usecase "Remove media from watchlist" as (UC9)
note bottom of (UC7) : Media is added to watched list
}

(UC1) --> (UC2)
(UC1) --> (UC3)
(UC1) --> (UC4)
(UC1) --> (UC5)
(UC1) ----> (UC10) : if admin
(UC1) ----> (UC11) : if admin
(UC3) --> (UC6)
(UC4) --> (UC6)
(UC5) --> (UC6)
(UC6) --> (UC7)
(UC6) --> (UC8)
(UC6) --> (UC9)

@enduml